-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 00:17:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OurWebsiteDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OurWebsiteDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OurWebsiteDB` DEFAULT CHARACTER SET utf8 ;
USE `OurWebsiteDB` ;

-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`table4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`table4` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`table6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`table6` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`table7`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`table7` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Client` (
  `idClient` INT NOT NULL,
  `nomClient` VARCHAR(45) NOT NULL,
  `prenomClient` VARCHAR(45) NOT NULL,
  `adresseClient` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idClient`, `Agent_idAgent`),
  CONSTRAINT `fk_Client_Agent1`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtable5_UNIQUE` ON `OurWebsiteDB`.`Client` (`id_client` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Agent` (
  `idAgent` INT NOT NULL,
  `nomAgent` VARCHAR(45) NOT NULL,
  `prenomAgent` VARCHAR(45) NOT NULL,
  `emailAgent` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAgent`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idAgent_UNIQUE` ON `OurWebsiteDB`.`Agent` (`idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Vol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Vol` (
  `idVol` INT NOT NULL,
  `destVol` VARCHAR(45) NOT NULL,
  `dateVol` VARCHAR(45) NOT NULL,
  `nb_pers_vol` VARCHAR(45) NOT NULL,
  `classe_vol` VARCHAR(45) NOT NULL,
  `prix_vol` VARCHAR(45) NOT NULL,
  `date_retour_vol` VARCHAR(45) NOT NULL,
  `cmp_vol` VARCHAR(45) NOT NULL,
  `type_dmd` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idVol`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Vol_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vol_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idVol_UNIQUE` ON `OurWebsiteDB`.`Vol` (`idVol` ASC) VISIBLE;

CREATE INDEX `fk_Vol_Client1_idx` ON `OurWebsiteDB`.`Vol` (`Client_id_client` ASC, `Client_nom_client` ASC, `Client_prenom_client` ASC, `Client_adresse` ASC, `Client_email_client` ASC) VISIBLE;

CREATE INDEX `fk_Vol_Agent1_idx` ON `OurWebsiteDB`.`Vol` (`Agent_idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Voiture` (
  `idtable12` INT NOT NULL,
  `id_vtr` VARCHAR(45) NOT NULL,
  `date_rest_vtr` VARCHAR(45) NOT NULL,
  `pays_vtr` VARCHAR(45) NOT NULL,
  `date_vtr` VARCHAR(45) NOT NULL,
  `prix_vtr` VARCHAR(45) NOT NULL,
  `cmp_vtr` VARCHAR(45) NOT NULL,
  `Voiturecol1` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idtable12`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Voiture_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voiture_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idVoiture_UNIQUE` ON `OurWebsiteDB`.`Voiture` (`idVoiture` ASC) VISIBLE;

CREATE INDEX `fk_Voiture_Client1_idx` ON `OurWebsiteDB`.`Voiture` (`Client_id_client` ASC, `Client_nom_client` ASC, `Client_prenom_client` ASC, `Client_adresse` ASC, `Client_email_client` ASC) VISIBLE;

CREATE INDEX `fk_Voiture_Agent1_idx` ON `OurWebsiteDB`.`Voiture` (`Agent_idAgent` ASC, `Agent_nom_agent` ASC, `Agent_prenom_agent` ASC, `Agent_Email` ASC, `Agent_adresse` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Hotel` (
  `idHotel` INT NOT NULL,
  `adrHotel` VARCHAR(45) NOT NULL,
  `catgHotel` VARCHAR(45) NOT NULL,
  `dateHotel` VARCHAR(45) NOT NULL,
  `nbPersHotel` VARCHAR(45) NOT NULL,
  `duree` VARCHAR(45) NOT NULL,
  `prixHotel` VARCHAR(45) NOT NULL,
  `type_dmd` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idHotel`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Hotel_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idHotel_UNIQUE` ON `OurWebsiteDB`.`Hotel` (`idHotel` ASC) VISIBLE;

CREATE INDEX `fk_Hotel_Client1_idx` ON `OurWebsiteDB`.`Hotel` (`Client_id_client` ASC, `Client_nom_client` ASC, `Client_prenom_client` ASC, `Client_adresse` ASC, `Client_email_client` ASC) VISIBLE;

CREATE INDEX `fk_Hotel_Agent1_idx` ON `OurWebsiteDB`.`Hotel` (`Agent_idAgent` ASC) VISIBLE;

CREATE INDEX `fk_Hotel_Voiture1_idx` ON `OurWebsiteDB`.`Hotel` (`Hotelcol1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Offre` (
  `idOffre` INT NOT NULL,
  `nomOffre` VARCHAR(45) NOT NULL,
  `date_dep_offr` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `durée` VARCHAR(45) NOT NULL,
  `ville_depart` VARCHAR(45) NOT NULL,
  `prix` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NOT NULL,
  `type_dmd` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idOffre`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Offre_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offre_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idOffre_UNIQUE` ON `OurWebsiteDB`.`Offre` (`idOffre` ASC) VISIBLE;

CREATE INDEX `fk_Offre_Offre_idx` ON `OurWebsiteDB`.`Offre` (`Offre_idOffre` ASC, `Offre_Offrecol` ASC, `Offre_Offrecol1` ASC, `Offre_Offrecol2` ASC, `Offre_Offrecol3` ASC, `Offre_Offrecol4` ASC, `Offre_Offrecol5` ASC, `Offre_Offrecol6` ASC, `Offre_Offrecol7` ASC, `Offre_Offrecol8` ASC, `Offre_Offrecol9` ASC, `Offre_Offrecol10` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Offre` (
  `idOffre` INT NOT NULL,
  `nomOffre` VARCHAR(45) NOT NULL,
  `date_dep_offr` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `durée` VARCHAR(45) NOT NULL,
  `ville_depart` VARCHAR(45) NOT NULL,
  `prix` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NOT NULL,
  `type_dmd` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idOffre`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Offre_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offre_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idOffre_UNIQUE` ON `OurWebsiteDB`.`Offre` (`idOffre` ASC) VISIBLE;

CREATE INDEX `fk_Offre_Agent1_idx` ON `OurWebsiteDB`.`Offre` (`Agent_idAgent` ASC, `Agent_nom_agent` ASC, `Agent_prenom_agent` ASC, `Agent_Email` ASC, `Agent_adresse` ASC) VISIBLE;

CREATE INDEX `fk_Offre_Client1_idx` ON `OurWebsiteDB`.`Offre` (`Client_id_client` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Reservation` (
  `idReservation` INT NOT NULL,
  `Reservationcol` VARCHAR(45) NOT NULL,
  `Reservationcol1` VARCHAR(45) NOT NULL,
  `Reservationcol2` VARCHAR(45) NOT NULL,
  `Reservationcol3` VARCHAR(45) NOT NULL,
  `Reservationcol4` VARCHAR(45) NOT NULL,
  `Reservationcol5` VARCHAR(45) NOT NULL,
  `Agent_idAgent` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idReservation`),
  CONSTRAINT `fk_Reservation_Agent1`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Reservation_Agent1_idx` ON `OurWebsiteDB`.`Reservation` (`Agent_idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Agent` (
  `idAgent` INT NOT NULL,
  `nomAgent` VARCHAR(45) NOT NULL,
  `prenomAgent` VARCHAR(45) NOT NULL,
  `emailAgent` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAgent`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idAgent_UNIQUE` ON `OurWebsiteDB`.`Agent` (`idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Client` (
  `idClient` INT NOT NULL,
  `nomClient` VARCHAR(45) NOT NULL,
  `prenomClient` VARCHAR(45) NOT NULL,
  `adresseClient` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idClient`, `Agent_idAgent`),
  CONSTRAINT `fk_Client_Agent1`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Client_Agent1_idx` ON `OurWebsiteDB`.`Client` (`Agent_idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Hotel` (
  `idHotel` INT NOT NULL,
  `adrHotel` VARCHAR(45) NOT NULL,
  `catgHotel` VARCHAR(45) NOT NULL,
  `dateHotel` VARCHAR(45) NOT NULL,
  `nbPersHotel` VARCHAR(45) NOT NULL,
  `duree` VARCHAR(45) NOT NULL,
  `prixHotel` VARCHAR(45) NOT NULL,
  `type_dmd` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idHotel`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Hotel_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Hotel_Agent2_idx` ON `OurWebsiteDB`.`Hotel` (`Agent_idAgent` ASC) VISIBLE;

CREATE INDEX `fk_Hotel_Client2_idx` ON `OurWebsiteDB`.`Hotel` (`Client_idClient` ASC, `Client_Agent_idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Vol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Vol` (
  `idVol` INT NOT NULL,
  `destVol` VARCHAR(45) NOT NULL,
  `dateVol` VARCHAR(45) NOT NULL,
  `nb_pers_vol` VARCHAR(45) NOT NULL,
  `classe_vol` VARCHAR(45) NOT NULL,
  `prix_vol` VARCHAR(45) NOT NULL,
  `date_retour_vol` VARCHAR(45) NOT NULL,
  `cmp_vol` VARCHAR(45) NOT NULL,
  `type_dmd` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idVol`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Vol_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vol_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Vol_Agent2_idx` ON `OurWebsiteDB`.`Vol` (`Agent_idAgent` ASC) VISIBLE;

CREATE INDEX `fk_Vol_Client2_idx` ON `OurWebsiteDB`.`Vol` (`Client_idClient` ASC, `Client_Agent_idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Offre` (
  `idOffre` INT NOT NULL,
  `nomOffre` VARCHAR(45) NOT NULL,
  `date_dep_offr` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `durée` VARCHAR(45) NOT NULL,
  `ville_depart` VARCHAR(45) NOT NULL,
  `prix` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NOT NULL,
  `type_dmd` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idOffre`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Offre_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offre_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Offre_Agent2_idx` ON `OurWebsiteDB`.`Offre` (`Agent_idAgent` ASC) VISIBLE;

CREATE INDEX `fk_Offre_Client2_idx` ON `OurWebsiteDB`.`Offre` (`Client_idClient` ASC, `Client_Agent_idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`Voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`Voiture` (
  `idtable12` INT NOT NULL,
  `id_vtr` VARCHAR(45) NOT NULL,
  `date_rest_vtr` VARCHAR(45) NOT NULL,
  `pays_vtr` VARCHAR(45) NOT NULL,
  `date_vtr` VARCHAR(45) NOT NULL,
  `prix_vtr` VARCHAR(45) NOT NULL,
  `cmp_vtr` VARCHAR(45) NOT NULL,
  `Voiturecol1` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Client_Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idtable12`, `Agent_idAgent`, `Client_idClient`, `Client_Agent_idAgent`),
  CONSTRAINT `fk_Voiture_Agent2`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voiture_Client2`
    FOREIGN KEY (`Client_idClient` , `Client_Agent_idAgent`)
    REFERENCES `OurWebsiteDB`.`Client` (`idClient` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Voiture_Agent2_idx` ON `OurWebsiteDB`.`Voiture` (`Agent_idAgent` ASC) VISIBLE;

CREATE INDEX `fk_Voiture_Client2_idx` ON `OurWebsiteDB`.`Voiture` (`Client_idClient` ASC, `Client_Agent_idAgent` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `OurWebsiteDB`.`table13`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`table13` (
)
ENGINE = InnoDB;

USE `OurWebsiteDB` ;

-- -----------------------------------------------------
-- Placeholder table for view `OurWebsiteDB`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurWebsiteDB`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `OurWebsiteDB`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OurWebsiteDB`.`view1`;
USE `OurWebsiteDB`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
